RANDOM_SEED: 0
AMP: true
CUDNN_BENCHMARK: true
CUDNN_DETERMINISTIC: false

DATA:
  ROOT: "/export/home/Projects/vislang-infomax/datasets/serialized/"
  NEGATIVE_SAMPLING: "normal"

  IMAGE_CROP_SIZE: 224
  USE_PERCENTAGE: 100.0
  USE_SINGLE_CAPTION: false
  IMAGE_TRANSFORM_TRAIN: [
    "random_resized_crop",
    "horizontal_flip",
    "color_jitter",
    "normalize",
    ]
MODEL:
  NAME: "captions"
  VISUAL:
    NETWORK_NAME: "resnet50"
    FEATURE_SIZE: 2048
  TEXTUAL:
    NAME: "train_sbert"
    PRETRAINED: False
    NETWORK_NAME: "bert-base-uncased"
    FEATURE_SIZE: 768
    TRANSFORM: False
    NUM_HIDDEN_LAYERS: 2
  LOSS:
    NAME: "jsd"
    TYPE: "dot"

OPTIM:
  OPTIMIZER_NAME: "sgd"
  SGD_MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  CLIP_GRAD_NORM: 10.0

  LOOKAHEAD:
    USE: true
    ALPHA: 0.5
    STEPS: 5

  BATCH_SIZE: 512
  CNN_LR: 0.2
  LR: 0.001
  TRANS_LR: 0.001
  MIN_LR_MULT: 0.0
  NUM_ITERATIONS: 200000

  WARMUP_STEPS: 10000
  LR_DECAY_NAME: "cosine"

RUN_ID: "bsab_512"
