RANDOM_SEED: 0
AMP: true
CUDNN_BENCHMARK: true
CUDNN_DETERMINISTIC: false

DATA:
  ROOT: "/export/home/Projects/vislang-infomax/datasets/serialized/"
  NEGATIVE_SAMPLING: "normal"

  IMAGE_CROP_SIZE: 224
  USE_PERCENTAGE: 100.0
  USE_SINGLE_CAPTION: false
  IMAGE_TRANSFORM_TRAIN: [
    "random_resized_crop",
    "color_jitter",
    "normalize",
    ]
MODEL:
  NAME: "captions"
  VISUAL:
    NETWORK_NAME: "resnet50"
    FEATURE_SIZE: 2048
  TEXTUAL:
    NAME: "train_sbert"
    NETWORK_NAME: "sentence-transformers/paraphrase-mpnet-base-v2"
    FEATURE_SIZE: 768
  LOSS:
    NAME: "jsd"
    TYPE: "dot"

OPTIM:
  OPTIMIZER_NAME: "sgd"
  SGD_MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  CLIP_GRAD_NORM: 10.0

  LOOKAHEAD:
    USE: true
    ALPHA: 0.5
    STEPS: 5

  BATCH_SIZE: 1024
  CNN_LR: 0.2
  TRANS_LR: 0.001
  LR: 0.001
  NUM_ITERATIONS: 250000

  WARMUP_STEPS: 10000
  LR_DECAY_NAME: "cosine"

RUN_ID: "fs_bs1024_ni250k_v2"
